LeaveRequest.ASP/LeaveRequest.ASP/Controllers/EmployeeLeaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LeaveRequest.ASP.Common.Interface;
using LeaveRequest.ASP.DataAccess.Param;

namespace LeaveRequest.ASP.Controllers
{
    public class EmployeeLeaveController : Controller
    {
        private readonly IEmployeeLeaveService _employeeLeaveService;
        public EmployeeLeaveController() { }
        public EmployeeLeaveController(IEmployeeLeaveService employeeLeaveService)
        {
            this._employeeLeaveService = employeeLeaveService;
        }
        // GET: EmployeeLeave
        public ActionResult Index()
        {
            if (Session["Id"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login","Login");
            }
        }
        public ActionResult Create(int? id)
        {
            id = Convert.ToInt16(Session["Id"]);
            var employee = _employeeLeaveService.Get(id);
            var employeeleaveparam = new EmployeeLeaveParam(employee);

            IEnumerable<SelectListItem> _leavetype = _employeeLeaveService.LeaveType().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name

            });
            ViewBag.leavetype = _leavetype;
            return View(employeeleaveparam);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeLeaveParam employeeleaveparam)
        {
            if (ModelState.IsValid)
            {
                _employeeLeaveService.Insert(employeeleaveparam);
                return RedirectToAction("Index");
            }

            return View(employeeleaveparam);
        }
        [HttpPost]
        public ActionResult GetTypeLeave(int? id)
        {
                var obj = _employeeLeaveService.GetTypeLeave(id);
                return Content(obj.TotalDays.ToString());
        }
    }
}

LeaveRequest.ASP/LeaveRequest.ASP/Views/EmployeeLeave/Index.cshtml
@model LeaveRequest.ASP.DataAccess.Param.EmployeeParam
    @{
        ViewBag.Title = "Index";
    }

    <h2>Index From EmployeeLeave</h2>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Leave Request", "Index", "EmployeeLeave", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "EmployeeLeave")</li>
                    <li>@Html.ActionLink("Leave Request", "Create", "EmployeeLeave")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>